name: Build ED64 Example ROM
 
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        releasetype: [ 'debug', 'release' ]
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code

      - name: Install Libdragon container
        run: |
          sudo npm install -g libdragon
          libdragon install

      - name: Setup Build environment
        run: |
          cd ${{ github.workspace }}/ED64-XIO/
          mkdir bin && mkdir bin/release && mkdir bin/debug && mkdir obj
          libdragon start

      - name: Build ROM
        run: cd ${{ github.workspace }}/ED64-XIO/ && libdragon make ${{ matrix.releasetype }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ED64-XIO-SAMPLE_N64_ROM-${{ matrix.releasetype }}
          path: ${{ github.workspace }}/ED64-XIO/bin/${{ matrix.releasetype }}/ED64-XIO-SAMPLE.v64
