name: Build ED64 Example ROM
 
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code

      - name: Install Libdragon container
        run: |
          # TODO: the sample needs updating. This is the last known compatible version!
          # Remove the @1.3.15 to run at latest.
          # And, this would also involve having a git subtree of the libdragon version.
          # which would make it easier to show "custom" changes to source.
          sudo npm install -g libdragon@1.3.15
          libdragon download

      - name: Setup Build environment
        run: |
          cd ${{ github.workspace }}/ED64-XIO/
          mkdir bin && mkdir obj
          libdragon start

      - name: Build ROM
        run: cd ${{ github.workspace }}/ED64-XIO/ && libdragon make

      - name: Upload Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ED64-XIO-SAMPLE_N64_ROM
          path: ${{ github.workspace }}/ED64-XIO/bin/ED64-XIO-SAMPLE.v64